select PRODUCT_ID,
       PRODUCT_TITLE,
       PRODUCT_DATE,
       PRODUCT_IMG1,
       PRODUCT_IMG2,
       PRODUCT_IMG3,
       PRODUCT_PRICE,
       PRODUCT_DESC,
       CATEGORY_ID,
       PRODUCT_QUANTITY,
       TRADER_ID
  from PRODUCT WHERE TRADER_ID IN (SELECT TRADER_ID FROM TRADER WHERE TRADER_EMAIL=:SESSION_EMAIL);